//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linguaevum.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GUILang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GUILang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Linguaevum.App_GlobalResources.GUILang", typeof(GUILang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autocomplete.
        /// </summary>
        public static string Autocomplete {
            get {
                return ResourceManager.GetString("Autocomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aksara Bali.
        /// </summary>
        public static string Bali {
            get {
                return ResourceManager.GetString("Bali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aksara IME.
        /// </summary>
        public static string Brahmic {
            get {
                return ResourceManager.GetString("Brahmic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold SHIFT down for Examples.
        /// </summary>
        public static string DictGuide {
            get {
                return ResourceManager.GetString("DictGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuzhounese.
        /// </summary>
        public static string Eastmin {
            get {
                return ResourceManager.GetString("Eastmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakka.
        /// </summary>
        public static string Hakka {
            get {
                return ResourceManager.GetString("Hakka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hanja Korean.
        /// </summary>
        public static string Hankor {
            get {
                return ResourceManager.GetString("Hankor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hán - Nôm.
        /// </summary>
        public static string Hannom {
            get {
                return ResourceManager.GetString("Hannom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IME.
        /// </summary>
        public static string IME {
            get {
                return ResourceManager.GetString("IME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Method Editor for Hán-Nôm, Sawndip, Hanja Korean, and Chinese script in Modern Chinese varieties and Middle Chinese..
        /// </summary>
        public static string IMEDes {
            get {
                return ResourceManager.GetString("IMEDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Method Editor.
        /// </summary>
        public static string IMETitle {
            get {
                return ResourceManager.GetString("IMETitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tai Tham.
        /// </summary>
        public static string Lanna {
            get {
                return ResourceManager.GetString("Lanna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lao.
        /// </summary>
        public static string Lao {
            get {
                return ResourceManager.GetString("Lao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lao.
        /// </summary>
        public static string Laos {
            get {
                return ResourceManager.GetString("Laos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linguaevum.
        /// </summary>
        public static string Linguevity {
            get {
                return ResourceManager.GetString("Linguevity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandarin.
        /// </summary>
        public static string Mandarin {
            get {
                return ResourceManager.GetString("Mandarin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Chinese.
        /// </summary>
        public static string Midchinese {
            get {
                return ResourceManager.GetString("Midchinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devanāgarī.
        /// </summary>
        public static string Nagari {
            get {
                return ResourceManager.GetString("Nagari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonology.
        /// </summary>
        public static string Phono {
            get {
                return ResourceManager.GetString("Phono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronunciation instruction and Text-to-speech tool with human sounding..
        /// </summary>
        public static string PhonoDes {
            get {
                return ResourceManager.GetString("PhonoDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saw-ndip.
        /// </summary>
        public static string Sawndip {
            get {
                return ResourceManager.GetString("Sawndip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinogram IME.
        /// </summary>
        public static string Sinic {
            get {
                return ResourceManager.GetString("Sinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sino - Lanna.
        /// </summary>
        public static string SinoLanna {
            get {
                return ResourceManager.GetString("SinoLanna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sino - Lao.
        /// </summary>
        public static string SinoLao {
            get {
                return ResourceManager.GetString("SinoLao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sino - Tai-Dam.
        /// </summary>
        public static string SinoTaidam {
            get {
                return ResourceManager.GetString("SinoTaidam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sino - Tai-Lü.
        /// </summary>
        public static string SinoTailue {
            get {
                return ResourceManager.GetString("SinoTailue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sino - Tai-Nüa.
        /// </summary>
        public static string SinoTainuea {
            get {
                return ResourceManager.GetString("SinoTainuea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sino - Tai-Yai.
        /// </summary>
        public static string SinoTaiyai {
            get {
                return ResourceManager.GetString("SinoTaiyai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sino - Tai-Yo.
        /// </summary>
        public static string SinoTaiyo {
            get {
                return ResourceManager.GetString("SinoTaiyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sino - Siamese.
        /// </summary>
        public static string SinoThai {
            get {
                return ResourceManager.GetString("SinoThai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hokkien.
        /// </summary>
        public static string Southmin {
            get {
                return ResourceManager.GetString("Southmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sino - Tày.
        /// </summary>
        public static string Tay {
            get {
                return ResourceManager.GetString("Tay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai.
        /// </summary>
        public static string Thailand {
            get {
                return ResourceManager.GetString("Thailand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Linguaevum.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wu Chinese.
        /// </summary>
        public static string Wu {
            get {
                return ResourceManager.GetString("Wu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonese.
        /// </summary>
        public static string Yue {
            get {
                return ResourceManager.GetString("Yue", resourceCulture);
            }
        }
    }
}
